RepoSettings:
  owner: valer1435
  name: RepoPilot

DataLoader:
  enable: False
  docs:
    collection_name: "fedot"
    site: "https://fedot.readthedocs.io/en/latest/"
    extensions: ["/", '.html']
  code:
    collection_name: "fedot_code"
    repo_owner: "aimclub"
    repo_name: "fedot"
    branch: "master"
    extensions: [".py"]
    folders: ["fedot"]

VectorStore:
  host: "localhost"
  port: 6333
  collections:
    - name: 'fedot'
      emb_dim: 1024
      agent_name: 'Documentation'
      description: 'Used to provide general information, examples about framework'
    - name: 'fedot_code'
      emb_dim: 1024
      agent_name: 'CodeBase'
      description: 'Used to provide source code of Fedot framework.'
Embedding:
  provider: 'huggingface'
  config:
    model_name: 'WhereIsAI/UAE-Large-V1'
    trust_remote_code: true
    device: 'cpu'
Preprocessor:
Retriever:
  top_k: 5
  sparse_top_k: 5
LLMCaller:
  token_variable: 'OPENAI_API_KEY'
  llm:
    model: 'deepseek-coder'
    api_base: 'https://api.deepseek.com'
    temperature: 0

