RepoSettings:
  owner: valer1435
  name: RepoPilot

DataLoader:
  enable: False
  docs:
    collection_name: "vllm"
    site: "https://docs.vllm.ai/en/latest/"
    extensions: ["/", '.html']
  code:
    collection_name: "vllm_code"
    repo_owner: "vllm-project"
    repo_name: "vllm"
    branch: "main"
    extensions: [".py"]
    folders: ["vllm"]

VectorStore:
  host: "localhost"
  port: 6333
  collections:
    - name: 'vllm'
      emb_dim: 1024
      agent_name: 'Documentation'
      description: 'Used to provide general information, examples about framework'
    - name: 'vllm_code'
      emb_dim: 1024
      agent_name: 'CodeBase'
      description: 'Used to provide source code of VLLM framework. May be useful in questions about classes and 
      functions inside framework'
Embedding:
  provider: 'huggingface'
  config:
    model_name: 'WhereIsAI/UAE-Large-V1'
    trust_remote_code: true
    device: 'cuda'
Preprocessor:
Retriever:
  top_k: 5
  sparse_top_k: 5
LLMCaller:
  token_variable: 'OPENAI_API_KEY'
  llm:
    model: 'deepseek-coder'
    api_base: 'https://api.deepseek.com'
    temperature: 0

