RepoSettings:
  owner: valer1435
  name: RepoPilot

DataLoader:

VectorStore:
    - name: 'fedot'
      emb_dim: 1024
      agent_name: 'Documentation'
      description: 'Used to provide general information, examples about framework'
    - name: 'fedot_code'
      emb_dim: 1024
      agent_name: 'CodeBase'
      description: 'Used to provide source code of Fedot framework. May be useful in questions about classes and 
      functions inside framework'


Embedding:
  provider: 'huggingface'
  config:
    model_name: 'WhereIsAI/UAE-Large-V1'
    trust_remote_code: true
    device: 'cuda'

Reranker:
  enabled: True
  model_config:
    pretrained_model_name_or_path: 'jinaai/jina-reranker-v2-base-multilingual'
    config:
      torch_dtype: 'auto'
      trust_remote_code: True
    device: 'cuda'
  top_k: 5


Preprocessor:
Retriever:
  top_k: 5
  sparse_top_k: 5
LLMCaller:
  token_variable: 'OPENAI_API_KEY'
  llm:
    model: 'second-state/Mistral-Nemo-Instruct-2407-GGUF'
    api_base: 'http://localhost:5001/v1'
    temperature: 0

  task_prompt: "You are Q&A system over open-source automl library Fedot. You are given with chat history of some issue in github repository.
   Using the information contained in the context, try to understand current state of conversation and answer user question.
Respond only to the question asked, response should be concise and relevant to the question. If user asks questions about Fedot usage - prioritize API
examples first. Make you answer as detailed as you can. Format your answer as markdown for readability.
If the answer cannot be deduced from the context, do not give an answer.\n
-------------------\n
{context}\n
-------------------\n
Chat history :\n
{query}\n
Answer: 
"

