[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = false

[config]
custom_model_max_tokens=8000
model="openai/second-state/Mistral-Nemo-Instruct-2407-GGUF"
model_turbo="openai/second-state/Mistral-Nemo-Instruct-2407-GGUF"
fallback_models=["openai/second-state/Mistral-Nemo-Instruct-2407-GGUF"]